<?php

/**
 * @author Benjamin Barbier
 *
 */
class ConfigBean {
	
	/**
	 * @var bool
	 */
	private $splash_active;
	
	/**
	 * @var bool
	 */
	private $splash_test_active;
	
	/**
	 * @var bool
	 */
	private $wsi_first_load_mode_active;
	
	/**
	 * Getters & Setters
	 * Generated by http://www.shuchow.com/gettersetter.html
	 */
	public function isSplash_active() { return $this->splash_active; }
	public function isSplash_test_active() { return $this->splash_test_active; }
	public function isWsi_first_load_mode_active() { return $this->wsi_first_load_mode_active; }
	public function setSplash_active($x) { $this->splash_active = $x; }
	public function setSplash_test_active($x) { $this->splash_test_active = $x; }
	public function setWsi_first_load_mode_active($x) { $this->wsi_first_load_mode_active = $x; }
	
}